[versions]
junit = "6.0.3"
assertj = "3.27.7"
mockito = "5.23.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core" }
