plugins {
    id 'java'
    id 'com.senthora.gatlingfx'
    id 'jacoco-testkit-coverage'
}

gatlingfx {
    sourceSets = ['missing']
}

repositories {}

tasks.register('printDependencies') {
    doLast {
        configurations.testImplementation.dependencies.each {
            println "IMPLEMENTATION:${it.group}:${it.name}:${it.version}"
        }
        configurations.testRuntimeOnly.dependencies.each {
            println "RUNTIME:${it.group}:${it.name}:${it.version}"
        }
    }
}
