name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master, dev ]
    paths:
      - ".github/workflows/**"
      - "build.gradle"
      - "settings.gradle"
      - "gradle.properties"
      - "gradle/**"
      - "gradlew"
      - "gradlew.bat"
      - "src/**"
      - '!**/*.md'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-cleanup: never

      - name: Build project
        run: ./gradlew build -x test -x integrationTest -x functionalTest

      - name: Run tests
        run: ./gradlew test integrationTest functionalTest

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          disable_search: true
          fail_ci_if_error: true

      - name: Detect publication changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          base: ${{ github.ref_name }}
          filters: |
            publish:
              - 'src/**'
              - 'build.gradle'
              - 'gradle.properties'
              - 'settings.gradle'

      - name: Publish snapshot
        if: github.ref == 'refs/heads/dev' && steps.changes.outputs.publish == 'true'
        run: ./gradlew publish --info --console=plain | grep -E "Publish|Upload"
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
